pub mod atomic;
pub mod breadcrumb;
pub mod calendar;
pub mod chart_area;
pub mod chart_bar;
pub mod chart_common;
mod chart_flow;
pub mod chart_funnel;
pub mod chart_gauge;
pub mod chart_heatmap;
mod chart_label;
pub mod chart_line;
pub mod chart_mind_map;
pub mod chart_organization;
pub mod chart_pie;
pub mod chart_radar;
pub mod chart_registry;
pub mod chart_sankey;
pub mod chart_scatter;
pub mod chart_sparkline;
pub mod chart_treemap;
pub mod chart_word_cloud;
pub mod code_block;
pub mod collapse;
pub mod command_palette;
pub mod data_toolbar;
pub mod descriptions;
pub mod drawer;
pub mod dropdown;
pub mod feedback;
pub mod filter_panel;
pub mod image;
pub mod input;
pub mod input_advanced;
pub mod input_composites;
pub mod input_independent;
pub mod interactive;
pub mod layout;
pub mod list;
pub mod markdown_editor;
pub mod masonry;
pub mod menu;
pub mod mermaid_svg_viewer;
pub mod message;
pub mod metric_card;
pub mod mini_chart_card;
pub mod mobile_preview_frame;
pub mod modal;
pub mod navigation;
pub mod notification;
pub mod pagination;
pub mod popconfirm;
pub mod popover;
pub mod property_list;
pub mod qr_code;
pub mod rate;
pub mod runtime;
pub mod skeleton;
pub mod spin;
pub mod statistic;
pub mod status_timeline;
pub mod steps;
pub mod table;
pub mod timeline;
pub mod tooltip;
pub mod tour;

/// Dependency-ordered registration shared by every native host.
pub fn script_mod(vm: &mut crate::makepad_widgets::ScriptVm) {
    atomic::script_mod(vm);
    chart_area::script_mod(vm);
    chart_bar::script_mod(vm);
    chart_funnel::script_mod(vm);
    chart_gauge::script_mod(vm);
    chart_heatmap::script_mod(vm);
    chart_line::script_mod(vm);
    chart_mind_map::script_mod(vm);
    chart_organization::script_mod(vm);
    chart_pie::script_mod(vm);
    chart_radar::script_mod(vm);
    chart_sankey::script_mod(vm);
    chart_scatter::script_mod(vm);
    chart_sparkline::script_mod(vm);
    chart_treemap::script_mod(vm);
    chart_word_cloud::script_mod(vm);
    feedback::script_mod(vm);
    input_independent::script_mod(vm);
    input_composites::script_mod(vm);
    input_advanced::script_mod(vm);
    calendar::script_mod(vm);
    collapse::script_mod(vm);
    descriptions::script_mod(vm);
    image::script_mod(vm);
    list::script_mod(vm);
    menu::script_mod(vm);
    qr_code::script_mod(vm);
    rate::script_mod(vm);
    layout::script_mod(vm);
    navigation::script_mod(vm);
    interactive::script_mod(vm);
    runtime::script_mod(vm);
    masonry::script_mod(vm);
    breadcrumb::script_mod(vm);
    pagination::script_mod(vm);
    steps::script_mod(vm);
    skeleton::script_mod(vm);
    spin::script_mod(vm);
    statistic::script_mod(vm);
    timeline::script_mod(vm);
    drawer::script_mod(vm);
    dropdown::script_mod(vm);
    message::script_mod(vm);
    modal::script_mod(vm);
    notification::script_mod(vm);
    code_block::script_mod(vm);
    command_palette::script_mod(vm);
    data_toolbar::script_mod(vm);
    filter_panel::script_mod(vm);
    markdown_editor::script_mod(vm);
    table::script_mod(vm);
    mermaid_svg_viewer::script_mod(vm);
    metric_card::script_mod(vm);
    mini_chart_card::script_mod(vm);
    mobile_preview_frame::script_mod(vm);
    property_list::script_mod(vm);
    status_timeline::script_mod(vm);
    tour::script_mod(vm);
    popconfirm::script_mod(vm);
    popover::script_mod(vm);
    tooltip::script_mod(vm);
}
