import { execFileSync } from "node:child_process";
import { readFileSync, appendFileSync, existsSync } from "node:fs";
const tag = process.env.RELEASE_TAG ?? "";
if (!/^web-v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(tag)) throw new Error("Invalid Web version tag");
if (existsSync("native")) throw new Error("Web releases must use the Web-only branch");
const git = (...args) => execFileSync("git", args, { encoding: "utf8" }).trim();
if (git("cat-file", "-t", "refs/tags/" + tag) !== "tag") throw new Error("Annotated tag required");
const revision = git("rev-parse", "refs/tags/" + tag + "^{commit}");
if (revision !== git("rev-parse", "HEAD")) throw new Error("Tag/checkout mismatch");
const version = JSON.parse(readFileSync("package.json", "utf8")).version;
if (tag !== "web-v" + version) throw new Error("Tag/Web package version mismatch");
if (process.env.GITHUB_OUTPUT) appendFileSync(process.env.GITHUB_OUTPUT, "tag=" + tag + "\nrevision=" + revision + "\n");
console.log("Validated Web " + tag + " at " + revision);
